hostData:
  default:
    defaultShell: zsh
    packages:
      brewTaps:
        - jesseduffield/lazygit
        - zunit-zsh/zunit
      brew:
        - act
        - antidote
        - atuin
        - bat
        - btop
        - cheat
        - dive
        - duckdb
        - eza
        - fastfetch
        - fd
        - figlet
        - fzf
        - gh
        - git-delta
        - go
        - grep
        - herdr
        - htop
        - humanlog
        - jesseduffield/lazygit/lazygit
        - jq
        - just
        - lazydocker
        - make
        - neovim
        - nmap
        - nvim
        - nvm
        - rclone
        - ripgrep
        - screen
        - starship
        - tig
        - tmux
        - vim
        - wget
        - yazi
        - yq
        - zoxide
      gnomeExtensions:
        - appindicatorsupport@rgcjonas.gmail.com
        - blur-my-shell@aunetx
        - caffeine@patapon.info
        - emoji-copy@felipeftn
        - just-perfection-desktop@just-perfection
      flatpak:
        - com.brave.Browser
        - com.discordapp.Discord
        - com.google.Chrome
        - com.mattjakeman.ExtensionManager
        - com.slack.Slack
        - com.spotify.Client
        - com.visualstudio.code
        - md.obsidian.Obsidian
        - net.nokyan.Resources
        - org.gimp.GIMP
        - org.gnome.PowerStats
        - org.localsend.localsend_app
        - org.mozilla.firefox
        - org.telegram.desktop
        - org.videolan.VLC
        - us.zoom.Zoom
  ci:
    packages:
      brew:
        - bats-core
        - hello
  coffee-sponge:
    packages:
      gnomeExtensions:
        - dash-to-dock@micxgx.gmail.com
        - logomenu@aryan_k
        - rectangle@acristoffers.me
        - Vitals@CoreCoding.com
      brew:
      brewCask:
        - 1password-cli
        - 1password-gui-linux
        - claude-code
        - jetbrains-toolbox-linux
      brewCaskTaps:
        - ublue-os/tap
      rpmOstree:
        - ghostty
        - zsh
      flatpak: []
  grease-monkey:
    packages:
      gnomeExtensions: []
      brew:
        - tailscale
      flatpak: []
  mac-4981:
    packages:
      brew:
        - awscli
        - awscli-local
        - aws-sam-cli
        - trivy
      brewCask:
        - caffeine
        - firefox
        - gas-mask
        - ghostty
        - gimp
        - jordanbaird-ice
        - microsoft-edge
        - obsidian
        - raycast
        - rectangle
        - spotify
        - stats
        - visual-studio-code
        - vlc
