on:
  pull_request:
  workflow_dispatch:

jobs:
  install-and-test-linux-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - fedora:43
          - ubuntu:25.10
    container:
      image: ${{ matrix.os }}
      options: --ulimit nofile=1024:1024
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies dnf
        run: dnf install -y git curl >/dev/null 2>&1 || echo "no dnf"
      - name: Update apt cache
        run: apt update >/dev/null 2>&1 || echo "no apt"
      - name: Install dependencies apt
        run: apt install -y git curl >/dev/null 2>&1 || echo "no apt"
      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/bin
      - name: Init the repo based off the current branch
        run: chezmoi init -S .
      - name: Show the chezmoi data
        run: chezmoi data -S .
      - name: Run the chezmoi apply
        run: chezmoi apply -S .
  install-and-test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /Users/runner/.local/bin
      - name: echo $PATH
        run: echo $PATH
      - name: which chezmoi
        run: which chezmoi
      - name: Init the repo based off the current branch
        run: chezmoi init -S .
      - name: Show the chezmoi data
        run: chezmoi data -S .
      - name: Run the chezmoi apply
        run: chezmoi apply -S .